### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Purpzie** [Purpzie/modmail#1]
- [ ] Mod message editing/deleting
- [ ] Attachments
- [ ] General cleanup (it's super messy rn)
- [ ] Setup & usage guide
